/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsPreviewRouteImport } from './routes/docs.preview'
import { Route as DocsUiTextFieldRouteImport } from './routes/docs.ui.text-field'
import { Route as DocsUiSelectFieldRouteImport } from './routes/docs.ui.select-field'
import { Route as DocsUiRegistryRouteImport } from './routes/docs.ui.registry'
import { Route as DocsUiDialogRouteImport } from './routes/docs.ui.dialog'
import { Route as DocsUiDataTableRouteImport } from './routes/docs.ui.data-table'
import { Route as DocsOverlayPopoverTooltipSheetRouteImport } from './routes/docs.overlay.popover-tooltip-sheet'
import { Route as DocsCoreDialogRouteImport } from './routes/docs.core.dialog'
import { Route as DocsCoreContractsRouteImport } from './routes/docs.core.contracts'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsPreviewRoute = DocsPreviewRouteImport.update({
  id: '/docs/preview',
  path: '/docs/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsUiTextFieldRoute = DocsUiTextFieldRouteImport.update({
  id: '/docs/ui/text-field',
  path: '/docs/ui/text-field',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsUiSelectFieldRoute = DocsUiSelectFieldRouteImport.update({
  id: '/docs/ui/select-field',
  path: '/docs/ui/select-field',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsUiRegistryRoute = DocsUiRegistryRouteImport.update({
  id: '/docs/ui/registry',
  path: '/docs/ui/registry',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsUiDialogRoute = DocsUiDialogRouteImport.update({
  id: '/docs/ui/dialog',
  path: '/docs/ui/dialog',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsUiDataTableRoute = DocsUiDataTableRouteImport.update({
  id: '/docs/ui/data-table',
  path: '/docs/ui/data-table',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsOverlayPopoverTooltipSheetRoute =
  DocsOverlayPopoverTooltipSheetRouteImport.update({
    id: '/docs/overlay/popover-tooltip-sheet',
    path: '/docs/overlay/popover-tooltip-sheet',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocsCoreDialogRoute = DocsCoreDialogRouteImport.update({
  id: '/docs/core/dialog',
  path: '/docs/core/dialog',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsCoreContractsRoute = DocsCoreContractsRouteImport.update({
  id: '/docs/core/contracts',
  path: '/docs/core/contracts',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs/preview': typeof DocsPreviewRoute
  '/docs/core/contracts': typeof DocsCoreContractsRoute
  '/docs/core/dialog': typeof DocsCoreDialogRoute
  '/docs/overlay/popover-tooltip-sheet': typeof DocsOverlayPopoverTooltipSheetRoute
  '/docs/ui/data-table': typeof DocsUiDataTableRoute
  '/docs/ui/dialog': typeof DocsUiDialogRoute
  '/docs/ui/registry': typeof DocsUiRegistryRoute
  '/docs/ui/select-field': typeof DocsUiSelectFieldRoute
  '/docs/ui/text-field': typeof DocsUiTextFieldRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs/preview': typeof DocsPreviewRoute
  '/docs/core/contracts': typeof DocsCoreContractsRoute
  '/docs/core/dialog': typeof DocsCoreDialogRoute
  '/docs/overlay/popover-tooltip-sheet': typeof DocsOverlayPopoverTooltipSheetRoute
  '/docs/ui/data-table': typeof DocsUiDataTableRoute
  '/docs/ui/dialog': typeof DocsUiDialogRoute
  '/docs/ui/registry': typeof DocsUiRegistryRoute
  '/docs/ui/select-field': typeof DocsUiSelectFieldRoute
  '/docs/ui/text-field': typeof DocsUiTextFieldRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs/preview': typeof DocsPreviewRoute
  '/docs/core/contracts': typeof DocsCoreContractsRoute
  '/docs/core/dialog': typeof DocsCoreDialogRoute
  '/docs/overlay/popover-tooltip-sheet': typeof DocsOverlayPopoverTooltipSheetRoute
  '/docs/ui/data-table': typeof DocsUiDataTableRoute
  '/docs/ui/dialog': typeof DocsUiDialogRoute
  '/docs/ui/registry': typeof DocsUiRegistryRoute
  '/docs/ui/select-field': typeof DocsUiSelectFieldRoute
  '/docs/ui/text-field': typeof DocsUiTextFieldRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs/preview'
    | '/docs/core/contracts'
    | '/docs/core/dialog'
    | '/docs/overlay/popover-tooltip-sheet'
    | '/docs/ui/data-table'
    | '/docs/ui/dialog'
    | '/docs/ui/registry'
    | '/docs/ui/select-field'
    | '/docs/ui/text-field'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs/preview'
    | '/docs/core/contracts'
    | '/docs/core/dialog'
    | '/docs/overlay/popover-tooltip-sheet'
    | '/docs/ui/data-table'
    | '/docs/ui/dialog'
    | '/docs/ui/registry'
    | '/docs/ui/select-field'
    | '/docs/ui/text-field'
  id:
    | '__root__'
    | '/'
    | '/docs/preview'
    | '/docs/core/contracts'
    | '/docs/core/dialog'
    | '/docs/overlay/popover-tooltip-sheet'
    | '/docs/ui/data-table'
    | '/docs/ui/dialog'
    | '/docs/ui/registry'
    | '/docs/ui/select-field'
    | '/docs/ui/text-field'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsPreviewRoute: typeof DocsPreviewRoute
  DocsCoreContractsRoute: typeof DocsCoreContractsRoute
  DocsCoreDialogRoute: typeof DocsCoreDialogRoute
  DocsOverlayPopoverTooltipSheetRoute: typeof DocsOverlayPopoverTooltipSheetRoute
  DocsUiDataTableRoute: typeof DocsUiDataTableRoute
  DocsUiDialogRoute: typeof DocsUiDialogRoute
  DocsUiRegistryRoute: typeof DocsUiRegistryRoute
  DocsUiSelectFieldRoute: typeof DocsUiSelectFieldRoute
  DocsUiTextFieldRoute: typeof DocsUiTextFieldRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/preview': {
      id: '/docs/preview'
      path: '/docs/preview'
      fullPath: '/docs/preview'
      preLoaderRoute: typeof DocsPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/ui/text-field': {
      id: '/docs/ui/text-field'
      path: '/docs/ui/text-field'
      fullPath: '/docs/ui/text-field'
      preLoaderRoute: typeof DocsUiTextFieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/ui/select-field': {
      id: '/docs/ui/select-field'
      path: '/docs/ui/select-field'
      fullPath: '/docs/ui/select-field'
      preLoaderRoute: typeof DocsUiSelectFieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/ui/registry': {
      id: '/docs/ui/registry'
      path: '/docs/ui/registry'
      fullPath: '/docs/ui/registry'
      preLoaderRoute: typeof DocsUiRegistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/ui/dialog': {
      id: '/docs/ui/dialog'
      path: '/docs/ui/dialog'
      fullPath: '/docs/ui/dialog'
      preLoaderRoute: typeof DocsUiDialogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/ui/data-table': {
      id: '/docs/ui/data-table'
      path: '/docs/ui/data-table'
      fullPath: '/docs/ui/data-table'
      preLoaderRoute: typeof DocsUiDataTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/overlay/popover-tooltip-sheet': {
      id: '/docs/overlay/popover-tooltip-sheet'
      path: '/docs/overlay/popover-tooltip-sheet'
      fullPath: '/docs/overlay/popover-tooltip-sheet'
      preLoaderRoute: typeof DocsOverlayPopoverTooltipSheetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/core/dialog': {
      id: '/docs/core/dialog'
      path: '/docs/core/dialog'
      fullPath: '/docs/core/dialog'
      preLoaderRoute: typeof DocsCoreDialogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/core/contracts': {
      id: '/docs/core/contracts'
      path: '/docs/core/contracts'
      fullPath: '/docs/core/contracts'
      preLoaderRoute: typeof DocsCoreContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsPreviewRoute: DocsPreviewRoute,
  DocsCoreContractsRoute: DocsCoreContractsRoute,
  DocsCoreDialogRoute: DocsCoreDialogRoute,
  DocsOverlayPopoverTooltipSheetRoute: DocsOverlayPopoverTooltipSheetRoute,
  DocsUiDataTableRoute: DocsUiDataTableRoute,
  DocsUiDialogRoute: DocsUiDialogRoute,
  DocsUiRegistryRoute: DocsUiRegistryRoute,
  DocsUiSelectFieldRoute: DocsUiSelectFieldRoute,
  DocsUiTextFieldRoute: DocsUiTextFieldRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
