import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";

type RegistryIndex = {
  items: readonly {
    name: string;
  }[];
};

const repoRoot = path.resolve(import.meta.dir, "..");
const registryIndexPath = path.join(repoRoot, "registry/default/registry.json");
const outputPath = path.join(repoRoot, "apps/docs/src/lib/default-registry-items.gen.ts");

function variableName(name: string): string {
  const pascalName = name
    .split("-")
    .map((part) => `${part[0]?.toUpperCase() ?? ""}${part.slice(1)}`)
    .join("");
  return `item${pascalName}`;
}

async function main() {
  const registry = JSON.parse(await readFile(registryIndexPath, "utf8")) as RegistryIndex;
  const imports = [
    `import registry from "../../../../registry/default/registry.json";`,
    ...registry.items.map((item) => {
      const binding = variableName(item.name);
      return `import ${binding} from "../../../../registry/default/items/${item.name}.json";`;
    }),
  ];
  const itemBindings = registry.items.map((item) => `  ${variableName(item.name)},`).join("\n");
  const contents = `${imports.join("\n")}

// Generated by scripts/generate-docs-registry-items.ts. Do not edit by hand.
export const defaultRegistry = registry;

export const defaultRegistryItems = [
${itemBindings}
] as const;
`;

  await writeFile(outputPath, contents);
}

await main();
