import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";

type RegistryIndex = {
  items: readonly RegistryIndexItem[];
};

type RegistryIndexItem = {
  description: string;
  name: string;
  title: string;
  type: string;
};

type RegistryFile = {
  path: string;
  target?: string;
  type: string;
};

type RegistryItem = {
  categories?: readonly string[];
  compatibility?: Record<string, string>;
  dependencies?: readonly string[];
  description: string;
  files: readonly RegistryFile[];
  keywords?: readonly string[];
  meta?: {
    accessibility?: string;
    anatomy?: readonly string[];
    api?: string;
    columns?: string;
    customization?: string;
    dataAttributes?: string;
    dataShape?: string;
    dependencies?: readonly string[];
    install?: string;
    limitations?: string;
    maturity?: string;
    parity?: Record<string, string>;
    parts?: readonly string[];
    routerAdapter?: string;
    sourceFiles?: readonly string[];
    ssr?: string;
    state?: string;
  };
  name: string;
  registryDependencies?: readonly string[];
  title: string;
  type: string;
  version?: string;
};

const repoRoot = path.resolve(import.meta.dir, "..");
const registryIndexPath = path.join(repoRoot, "registry/default/registry.json");
const outputPath = path.join(repoRoot, "apps/web/src/lib/registry-docs.gen.ts");

async function main() {
  const registry = JSON.parse(await readFile(registryIndexPath, "utf8")) as RegistryIndex;
  const items = await Promise.all(
    registry.items.map(async (item) => {
      const itemPath = path.join(repoRoot, "registry/default/items", `${item.name}.json`);
      return JSON.parse(await readFile(itemPath, "utf8")) as RegistryItem;
    }),
  );
  const docs = items.map((item) => ({
    accessibility: item.meta?.accessibility,
    anatomy: item.meta?.anatomy ?? item.meta?.parts ?? [],
    api: item.meta?.api,
    categories: item.categories ?? [],
    columns: item.meta?.columns,
    compatibility: item.compatibility ?? {},
    customization: item.meta?.customization,
    dataAttributes: item.meta?.dataAttributes,
    dataShape: item.meta?.dataShape,
    dependencies: item.meta?.dependencies ?? item.dependencies ?? [],
    description: item.description,
    files: item.files.map((file) => ({ path: file.path, target: file.target, type: file.type })),
    install: item.meta?.install ?? `shadcn add https://keystone-ui.dev/r/${item.name}.json`,
    keywords: item.keywords ?? [],
    limitations: item.meta?.limitations,
    maturity: item.meta?.maturity,
    name: item.name,
    parity: item.meta?.parity ?? {},
    registryDependencies: item.registryDependencies ?? [],
    routerAdapter: item.meta?.routerAdapter,
    sourceFiles: item.files.map((file) => file.target ?? file.path),
    ssr: item.meta?.ssr,
    state: item.meta?.state,
    title: item.title,
    type: item.type,
    version: item.version,
  }));
  const contents = `// Generated by scripts/generate-docs-registry-items.ts. Do not edit by hand.
export type RegistryDocFile = {
  path: string;
  target?: string;
  type: string;
};

export type RegistryDocItem = {
  accessibility?: string;
  anatomy: readonly string[];
  api?: string;
  categories: readonly string[];
  columns?: string;
  compatibility: Readonly<Record<string, string>>;
  customization?: string;
  dataAttributes?: string;
  dataShape?: string;
  dependencies: readonly string[];
  description: string;
  files: readonly RegistryDocFile[];
  install: string;
  keywords: readonly string[];
  limitations?: string;
  maturity?: string;
  name: string;
  parity: Readonly<Record<string, string>>;
  registryDependencies: readonly string[];
  routerAdapter?: string;
  sourceFiles: readonly string[];
  ssr?: string;
  state?: string;
  title: string;
  type: string;
  version?: string;
};

export const registryDocItems = ${JSON.stringify(docs, null, 2)} as const satisfies readonly RegistryDocItem[];
`;

  await writeFile(outputPath, contents);
}

await main();
