import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";

type RegistryIndex = {
  homepage: string;
  items: readonly RegistryIndexItem[];
};

type RegistryIndexItem = {
  description: string;
  name: string;
  title: string;
  type: string;
};

type RegistryFile = {
  path: string;
  target?: string;
  type: string;
};

type RegistryItem = {
  categories?: readonly string[];
  compatibility?: Record<string, string>;
  dependencies?: readonly string[];
  description: string;
  files: readonly RegistryFile[];
  keywords?: readonly string[];
  meta?: {
    accessibility?: string;
    anatomy?: readonly string[];
    api?: string;
    columns?: string;
    customization?: string;
    dataAttributes?: string;
    dataShape?: string;
    dependencies?: readonly string[];
    install?: string;
    limitations?: string;
    maturity?: string;
    parity?: Record<string, string>;
    parts?: readonly string[];
    routerAdapter?: string;
    sourceFiles?: readonly string[];
    ssr?: string;
    state?: string;
  };
  name: string;
  registryDependencies?: readonly string[];
  title: string;
  type: string;
  version?: string;
};

const repoRoot = path.resolve(import.meta.dir, "..");
const registryIndexPath = path.join(repoRoot, "registry/default/registry.json");
const docsOutputPath = path.join(repoRoot, "apps/web/src/lib/registry-docs.gen.ts");
const landingFileTreeOutputPath = path.join(repoRoot, "apps/web/src/lib/landing-file-tree.gen.ts");
const uiComponentSourcePathPattern = /^packages\/ui\/src\/components\/[^/]+\.tsx$/;

function isStableRegistryItem(item: Pick<RegistryItem, "meta">) {
  return item.meta?.maturity?.toLowerCase() === "stable";
}

function componentHref(name: string) {
  return `/docs/components/${name}`;
}

function registryItemUrl(homepage: string, name: string) {
  return `${homepage.replace(/\/$/, "")}/r/${name}.json`;
}

async function main() {
  const registry = JSON.parse(await readFile(registryIndexPath, "utf8")) as RegistryIndex;
  const items = await Promise.all(
    registry.items.map(async (item) => {
      const itemPath = path.join(repoRoot, "registry/default/items", `${item.name}.json`);
      return JSON.parse(await readFile(itemPath, "utf8")) as RegistryItem;
    }),
  );
  const docs = items.map((item) => ({
    accessibility: item.meta?.accessibility,
    anatomy: item.meta?.anatomy ?? item.meta?.parts ?? [],
    api: item.meta?.api,
    categories: item.categories ?? [],
    columns: item.meta?.columns,
    compatibility: item.compatibility ?? {},
    customization: item.meta?.customization,
    dataAttributes: item.meta?.dataAttributes,
    dataShape: item.meta?.dataShape,
    dependencies: item.meta?.dependencies ?? item.dependencies ?? [],
    description: item.description,
    files: item.files.map((file) => ({ path: file.path, target: file.target, type: file.type })),
    install: `shadcn add ${registryItemUrl(registry.homepage, item.name)}`,
    keywords: item.keywords ?? [],
    limitations: item.meta?.limitations,
    maturity: item.meta?.maturity,
    name: item.name,
    parity: item.meta?.parity ?? {},
    registryDependencies: item.registryDependencies ?? [],
    routerAdapter: item.meta?.routerAdapter,
    sourceFiles: item.files.map((file) => file.target ?? file.path),
    ssr: item.meta?.ssr,
    state: item.meta?.state,
    title: item.title,
    type: item.type,
    version: item.version,
  }));
  const docsContents = `// Generated by scripts/generate-docs-registry-items.ts. Do not edit by hand.
export type RegistryDocFile = {
  path: string;
  target?: string;
  type: string;
};

export type RegistryDocItem = {
  accessibility?: string;
  anatomy: readonly string[];
  api?: string;
  categories: readonly string[];
  columns?: string;
  compatibility: Readonly<Record<string, string>>;
  customization?: string;
  dataAttributes?: string;
  dataShape?: string;
  dependencies: readonly string[];
  description: string;
  files: readonly RegistryDocFile[];
  install: string;
  keywords: readonly string[];
  limitations?: string;
  maturity?: string;
  name: string;
  parity: Readonly<Record<string, string>>;
  registryDependencies: readonly string[];
  routerAdapter?: string;
  sourceFiles: readonly string[];
  ssr?: string;
  state?: string;
  title: string;
  type: string;
  version?: string;
};

export const registryDocItems = ${JSON.stringify(docs, null, 2)} as const satisfies readonly RegistryDocItem[];
`;
  const landingFileTreeItems = items
    .filter((item) => item.type === "registry:ui" && isStableRegistryItem(item))
    .flatMap((item) => {
      const file = item.files.find((candidate) =>
        uiComponentSourcePathPattern.test(candidate.path),
      );
      if (file == null) return [];

      return [
        {
          href: componentHref(item.name),
          path: file.path,
        },
      ];
    })
    .sort((a, b) => a.path.localeCompare(b.path));
  const landingFileTreeContents = `// Generated by scripts/generate-docs-registry-items.ts. Do not edit by hand.
export type LandingFileTreeItem = {
  href: string;
  path: string;
};

export const landingFileTreeItems = ${JSON.stringify(landingFileTreeItems, null, 2)} as const satisfies readonly LandingFileTreeItem[];
`;

  await Promise.all([
    writeFile(docsOutputPath, docsContents),
    writeFile(landingFileTreeOutputPath, landingFileTreeContents),
  ]);
}

await main();
