import registry from "../../../../registry/default/registry.json";
import itemAccordion from "../../../../registry/default/items/accordion.json";
import itemAccountSettings from "../../../../registry/default/items/account-settings.json";
import itemCn from "../../../../registry/default/items/cn.json";
import itemButton from "../../../../registry/default/items/button.json";
import itemSwitch from "../../../../registry/default/items/switch.json";
import itemCheckbox from "../../../../registry/default/items/checkbox.json";
import itemRadioGroup from "../../../../registry/default/items/radio-group.json";
import itemInput from "../../../../registry/default/items/input.json";
import itemTextarea from "../../../../registry/default/items/textarea.json";
import itemLabel from "../../../../registry/default/items/label.json";
import itemField from "../../../../registry/default/items/field.json";
import itemTextField from "../../../../registry/default/items/text-field.json";
import itemSelectField from "../../../../registry/default/items/select-field.json";
import itemSlider from "../../../../registry/default/items/slider.json";
import itemDatePicker from "../../../../registry/default/items/date-picker.json";
import itemTabs from "../../../../registry/default/items/tabs.json";
import itemCombobox from "../../../../registry/default/items/combobox.json";
import itemCommandMenu from "../../../../registry/default/items/command-menu.json";
import itemAutocomplete from "../../../../registry/default/items/autocomplete.json";
import itemDataTable from "../../../../registry/default/items/data-table.json";
import itemDataTableTanstackRouter from "../../../../registry/default/items/data-table-tanstack-router.json";
import itemCard from "../../../../registry/default/items/card.json";
import itemBadge from "../../../../registry/default/items/badge.json";
import itemSeparator from "../../../../registry/default/items/separator.json";
import itemCollapsible from "../../../../registry/default/items/collapsible.json";
import itemDialog from "../../../../registry/default/items/dialog.json";
import itemPopover from "../../../../registry/default/items/popover.json";
import itemHoverCard from "../../../../registry/default/items/hover-card.json";
import itemMenu from "../../../../registry/default/items/menu.json";
import itemDropdownMenu from "../../../../registry/default/items/dropdown-menu.json";
import itemContextMenu from "../../../../registry/default/items/context-menu.json";
import itemMenubar from "../../../../registry/default/items/menubar.json";
import itemNavigationMenu from "../../../../registry/default/items/navigation-menu.json";
import itemToast from "../../../../registry/default/items/toast.json";
import itemToolbar from "../../../../registry/default/items/toolbar.json";
import itemTooltip from "../../../../registry/default/items/tooltip.json";
import itemSheet from "../../../../registry/default/items/sheet.json";

// Generated by scripts/generate-docs-registry-items.ts. Do not edit by hand.
export const defaultRegistry = registry;

export const defaultRegistryItems = [
  itemAccordion,
  itemAccountSettings,
  itemCn,
  itemButton,
  itemSwitch,
  itemCheckbox,
  itemRadioGroup,
  itemInput,
  itemTextarea,
  itemLabel,
  itemField,
  itemTextField,
  itemSelectField,
  itemSlider,
  itemDatePicker,
  itemTabs,
  itemCombobox,
  itemCommandMenu,
  itemAutocomplete,
  itemDataTable,
  itemDataTableTanstackRouter,
  itemCard,
  itemBadge,
  itemSeparator,
  itemCollapsible,
  itemDialog,
  itemPopover,
  itemHoverCard,
  itemMenu,
  itemDropdownMenu,
  itemContextMenu,
  itemMenubar,
  itemNavigationMenu,
  itemToast,
  itemToolbar,
  itemTooltip,
  itemSheet,
] as const;
